### ISSUE TITLE
why the device size in `lsblk` and `df` not equal?

### ISSUE THREAD

**Issue by abbycin** [CodeImp/sblkdev#3]
the module param is given 100M size and `lsblk` is 100M too, but `df` shows only `89M`， why they are not equal?
the following is the commands and outputs from my machine
```bash
root@suse ~/sblkdev (master)# insmod sblkdev.ko catalog="sblkdev1,204800"
root@suse ~/sblkdev (master)# lsblk | sed -n '1p;$p'
NAME     MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sblkdev1 253:0    0  100M  0 disk 
root@suse ~/sblkdev (master)# 
root@suse ~/sblkdev (master)# mkfs.ext4 /dev/sblkdev1
mke2fs 1.47.0 (5-Feb-2023)
Creating filesystem with 102400 1k blocks and 25584 inodes
Filesystem UUID: c3e0c089-d5e9-4e2f-ba31-e5d4514c589d
Superblock backups stored on blocks: 
        8193, 24577, 40961, 57345, 73729

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done 

root@suse ~/sblkdev (master)# mount /dev/sblkdev1 /mnt
root@suse ~/sblkdev (master)# df -h | sed -n '1p;$p'
Filesystem      Size  Used Avail Use% Mounted on
/dev/sblkdev1    89M   46K   82M   1% /mnt
root@suse ~/sblkdev (master)# fdisk -l /dev/sblkdev1 
Disk /dev/sblkdev1: 100 MiB, 104857600 bytes, 204800 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
root@suse ~/sblkdev (master)# 
```

**Comment by CodeImp** [comment]
Hi.
Your question has nothing to do with the project.
But, I decided to ask your question to AI.
I was quite satisfied with his answer:
"
This is AI-generated content. You acknowledge that any output generated may not be accurate or complete. You must thoroughly review it before using in any way.
The device size reported by lsblk and the disk usage reported by df may differ due to their different ways of interpreting and measuring disk space.

lsblk displays the physical size of the block device, which typically represents the total size of the underlying disk or partition, including any unpartitioned space.

On the other hand, df shows the amount of disk space currently used and available within a file system. It takes into account the file system overhead, such as reserved blocks for the superuser, journaling, or filesystem metadata.

Additionally, differences can arise due to:

File system overhead: The file system consumes some space for its internal structures, which is not included in the available space reported by df.

Inaccurate partitioning: If the disk or partition is not properly aligned or has extra space due to specific requirements or misconfigurations, it may affect the reported sizes.

It's important to understand the specific calculations and factors involved in each command to interpret the reported sizes accurately.
"
